-- ==========================================================
-- CMS Diacritics Direct Overwrite Script (Bypasses RLS)
-- ==========================================================

UPDATE page_sections SET title_ro = 'Explorează pe Categorii', settings = '{}'::jsonb WHERE id = 'bf4dc806-5fc7-423c-8000-2640ac2b14d4';
UPDATE page_sections SET title_ro = 'Ce Spun Oaspeții Noștri', subtitle_ro = 'Ascultați experiențele celor care au vizitat Petricani 22', settings = '{}'::jsonb WHERE id = 'b17959bc-59ae-46f0-b9de-4d9c70dd5ade';
UPDATE page_sections SET title_ro = 'Întrebări Frecvente', subtitle_ro = 'Găsiți răspunsuri la cele mai frecvente întrebări despre proprietatea noastră', settings = '{}'::jsonb WHERE id = '15cf6d68-2280-4ec5-9e6d-23dd9b92f129';
UPDATE page_sections SET title_ro = 'Galerie Foto', subtitle_ro = 'Explorează spațiile și facilitățile proprietății', settings = '{}'::jsonb WHERE id = 'c5d0a931-85d8-41be-a42d-ac696006d059';
UPDATE page_sections SET title_ro = 'Contactați-ne', subtitle_ro = 'Suntem aici pentru a vă ajuta să găsiți configurația perfectă', settings = '{"hours_label_en":"Hours","hours_label_ro":"Program","phone_label_en":"Phone","phone_label_ro":"Telefon","address_label_en":"Address","address_label_ro":"Adresă"}'::jsonb WHERE id = 'c8c90d8c-f785-400f-b5d7-04e16494703d';
UPDATE page_sections SET title_ro = 'Facilități și Servicii', subtitle_ro = 'Toate facilitățile necesare pentru o experiență confortabilă', settings = '{"special_features_title_en":"Special Features","special_features_title_ro":"Facilități Speciale"}'::jsonb WHERE id = 'e4c0417e-03fc-4f36-81ed-8c1d5edf341e';
UPDATE page_sections SET title_ro = 'Caracteristici Cheie', subtitle_ro = 'Spatiu generos cu facilitati moderne pentru orice tip de utilizare', settings = '{}'::jsonb WHERE id = 'e12c3d72-92b7-4adf-a141-16c910221e73';
UPDATE page_sections SET title_ro = 'Descopera cum poti folosi spatiul de la Petricani 22', subtitle_ro = 'Inspiratie pentru locuire, birouri, evenimente si mai mult', settings = '{"intro_title_en":"Real ideas, useful tips, and creative examples","intro_title_ro":"Idei reale, sfaturi utile si exemple creative","intro_description_en":"To help you imagine how this versatile space can be used - from modern living to outdoor events or flexible workspaces.","intro_description_ro":"Pentru a-ti imagina ce se poate face cu aceasta proprietate versatila - de la locuire moderna la evenimente in aer liber sau spatii de lucru."}'::jsonb WHERE id = 'f967ce8f-1877-4808-8acc-34a783e1bed2';
UPDATE page_sections SET title_ro = 'Locație Privilegiată', subtitle_ro = 'În inima Bucureștiului cu acces facil la toate facilitățile', settings = '{"map_title_en":"Find us on the map","map_title_ro":"Găsește-ne pe hartă","nearby_title_en":"Nearby","nearby_title_ro":"În apropiere"}'::jsonb WHERE id = '8c8273c2-1206-4294-9737-80f464ddb94b';
UPDATE page_sections SET title_ro = 'Oază Urbană în Petricani: Mâncare, Evenimente & Locuit', subtitle_ro = 'Locație multifuncțională premium ce dispune de curte pentru evenimente, hub gastronomic dedicat Street Food/Horeca și unități de cazare individuale.', content_ro = '<p data-path-to-node="6">Vă prezentăm un concept versatil, conceput să integreze armonios trei piloni principali: evenimente în aer liber, gastronomie și ospitalitate. Spațiul include o curte generoasă, ideală pentru organizarea de evenimente private sau corporate, completată de o zonă tehnică special amenajată pentru operatori Horeca și food trucks. În plus, locația oferă confort prin camerele de închiriat disponibile, fiind soluția completă pentru proiecte de tip pop-up, festivaluri restrânse sau escapade urbane cu facilități incluse.</p>', settings = '{"cta1_en":"Request Custom Offer","cta1_ro":"Solicită Ofertă Personalizată","cta2_en":"Schedule Viewing","cta2_ro":"Programează Vizionare"}'::jsonb WHERE id = 'a13b34a6-61a4-4464-b4d2-a864c1fe612c';
